version: '3'
services: 
    nodejs:
        build:
            dockerfile: .dockerfile
            context: .
        image: nodejs-app
        container_name: nodejs
        ports: 
            - "3000:3000" 